name: nightly

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Run script
        run: python scripts/main.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "nightly - `date +'%Y-%m-%d'`"
